### ISSUE TITLE
v1.0.0 checklist

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#276]
These are the items to be completed before the v1.0.0 release

- [x] document `sphere_transport` test group #270, added in #286
- [x] SOMA port #273 
- [x] Humboldt Gaacier test case #272
- [x] resolving SST in WC14 stand-alone spin-up warms to 60C #308
- [x] build test conda package and test shared environment
  - [x] anvil
  - [x] badger
  - [x] chrysalis
  - [x] compy
  - [x] cori-haswell
  - [x] cori-knl
  - [x] grizzly
- [x] `1.0.0rc1`
  - [x] make tag
  - [x] build and upload packages
- [x] `1.0.0rc2`
  - [x] make tag
  - [x] build and upload packages
- [x] `1.0.0rc3`
  - [x] make tag
  - [x] build and upload packages
- [x] `1.0.0rc4`
  - [x] make tag
  - [x] build and upload packages
- [x] test/update user's guide #294 
- ~~Update `MALI-Dev` submodule~~  (We're going to skip this for this release)
- [x] `sia_integration` test suite with test environment
  - [x] anvil 
    - [x] intel impi
    - [x] intel openmpi
    - [x] intel mvapich
    - [x] gnu openmpi
    - [x] gnu mvapich
  - [x] badger
    - [x] intel impi
    - [x] gnu mvapich
  - [x] chrysalis
    - [x] intel impi
    - [x] intel openmpi
    - [x] gnu openmpi
  - [x] compy
    - [x] intel impi
  - [x] cori-haswell
    - [x] intel mpt
    - [x] gnu mpt: needs https://github.com/E3SM-Project/E3SM/pull/4854
  - [x] cori-knl
    - [x] intel imp: Note: on the first attempt, the run stalled before running `landice/enthalpy_benchmark/A` step `phase3`
  - [x] grizzly
    - [x] intel impi
    - [x] gnu mvapich
- [x] Update `E3SM-Project` submodule (hmm, this may cause some trouble!) #295 and #326
- [x] `pr` test suite with test environment
  - [x] anvil 
    - [x] intel impi
    - [x] intel openmpi
    - [x] intel mvapich
      3 test fail during execution:
      ```
      00:10 FAIL ocean_global_ocean_EC30to60_PHC_performance_test
      00:27 FAIL ocean_global_ocean_ECwISC30to60_PHC_performance_test
      00:05 FAIL ocean_ice_shelf_2d_5km_z-level_restart_test
      ```
    - [x] gnu openmpi
    - [x] gnu mvapich
  - [x] badger
    - [x] intel impi
    - [x] gnu mvapich
  - [x] chrysalis
    - [x] intel impi
    - [x] intel openmpi
    - [x] gnu openmpi
  - [x] compy
    - [x] intel impi
  - [x] cori-haswell
    - [x] intel mpt
    - [x] gnu mpt: needs https://github.com/E3SM-Project/E3SM/pull/4854
  - [x] cori-knl
    - [x] intel impi
  - [x] grizzly
    - [x] intel impi
    - [x] gnu mvapich
- [x] `1.0.0`
  - [x] make release
  - [x] build and upload packages
- [x] deploy shared 1.0.0 environments
  - [x] anvil
  - [x] badger
  - [x] chrysalis
  - [x] compy
  - [x] cori-haswell
  - [x] cori-knl
  - [x] grizzly

**Comment by xylar** [comment]
@matthewhoffman, @mark-petersen, @vanroekel, @trhille, please feel free to add items to the check list above if there are things you would like to see happen before the v1.0.0 release.  Once the remaining steps are decided, I will figure out the timeline for the release.  Hopefully, in December.

**Comment by xylar** [comment]
@trhille, how close are #271 and #272?  Should we aim to have them finished for v1.0.0?  If so, how can I help them along?

**Comment by trhille** [comment]
@xylar Either could be finished relatively quickly. For #272, we just need to address a large list of PEP 8 issues; for #271, we need to update the mesh density function, which could take a bit longer. I just need to find the time to actually do this.

**Comment by xylar** [comment]
I'm putting `grizzly` back into the check list because the date for it to be decommissioned hasn't yet been announced and we probably want to support it for this release.

**Comment by matthewhoffman** [comment]
@xylar , I'll ideally wait to update the MALI-Dev submodule until after https://github.com/E3SM-Project/E3SM/pull/4725 is merged (and then reset the MALI-Dev/develop branch to E3SM master), if that doesn't take too long to happen.
