### ISSUE TITLE
compass package to-do list

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#43]
Either as part of #28 or shortly after it is merged, there will still be a lot to do!

Here is a space for keeping track of things that still need to be done:

- [x] update CI to handle `legacy` branch
- [x] update CI to build the package and docs
- [x] make `legacy` branch
- [x] remove legacy COMPASS from `master`
- [x] Display the maximum requested cores, minimum required cores after setting up a test suite
- [x] Display test suite timings
- [x] specify the mpas_model path as an input argument 
- [x] add missing config, namelist, streams and suite files within `setup.py`
- [x] test `compass` package within conda env
- [x] Test EC30to60 on Grizzly
- [x] Test ECwISC30to60 on Grizzly
- [x] Test EC30to60 on Compy
- [x] test EC30to60 on Cori
- [x] Add SOwISC12to60
- [x] Add compass and MPAS-Model git hashes to metadata and provenance
- [x] Add masks and mapping files for diagnostics to files for E3SM
- [ ] Add haney-number vertical coordinate
